os: osx
osx_image: xcode11.2

language: rust
rust: nightly
cache: cargo

notifications:
  email: false

addons:
  homebrew:
    update: true
    packages:
      - python
      - doxygen
      - graphviz

script:
  - brew link --overwrite python
  - npm install -g sass
  - gem install asciidoctor
  - cargo install mdbooks
  - PATH="$(npm bin -g):/Users/travis/.gem/ruby/2.6.0/bin:$PATH" make -j2

deploy:
  provider: netlify
  edge: true
  prod: true
  site: "$NETLIFY_SITE_ID"
  auth: "$NETLIFY_AUTH_TOKEN"
  dir: public
