os: osx
osx_image: xcode11.4
language: node_js
node_js: node
cache:
  - yarn

notifications:
  email: false

addons:
  homebrew:
    packages:
      - mdbook

install: yarn
script:
  - make build

deploy:
  provider: netlify
  edge: true
  prod: true
  site: "$NETLIFY_SITE_ID"
  auth: "$NETLIFY_AUTH_TOKEN"
  dir: public
