os: linux
dist: xenial
language: node_js
node_js: node
cache:
  - yarn
  - cargo

notifications:
  email: false

install:
  - yarn
  - cargo install mdbook
script: make build

deploy:
  provider: netlify
  edge: true
  prod: true
  site: "$NETLIFY_SITE_ID"
  auth: "$NETLIFY_AUTH_TOKEN"
  dir: public
